# run on container environment
sudo: false

language: php

notifications:
    email:
        on_success: change
        on_failure: always

php:
  - 7.1
  - 5.6
  - 5.3

env:
  # WP nightly:
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=1
  # WP latest stable:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  # WP previous stable:
  - WP_VERSION=4.5 WP_MULTISITE=0
  - WP_VERSION=4.5 WP_MULTISITE=1

matrix:
  fast_finish: true
  include:
    - php: hhvm
      env: WP_VERSION=nightly WP_MULTISITE=0
      sudo: required
      dist: trusty
      group: edge
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
    - php: hhvm
      env: WP_VERSION=nightly WP_MULTISITE=1
      sudo: required
      dist: trusty
      group: edge
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
  allow_failures:
    # allow failures on WP nightlies:
    - env: WP_VERSION=nightly WP_MULTISITE=0
    - env: WP_VERSION=nightly WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - if [[ "$WP_VERSION" == "latest" ]]; then if find . -not \( -path ./vendor -prune \) -not \( -path ./features -prune \) -not \( -path ./tests/phpunit/includes/dummy-closures.php -prune \) -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi; fi;
    - phpunit -v
