# run on container environment
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

language: php

notifications:
  email:
    on_success: change
    on_failure: always

php:
  - 7.2
  - 5.6

env:
  # WP latest stable:
  - WP_VERSION=latest
  # WP nightly:
  - WP_VERSION=nightly

matrix:
  fast_finish: true

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    fi

install:
  - composer install

before_script:
  - php --version
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - composer test
