# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  release:
    types: [published]

concurrency: WordPress.org

permissions:
  contents: read
  issues: write

jobs:
  test:
    name: Deploy Tag
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-tag.yml@trunk
    with:
      plugin: query-monitor
      readme: readme.txt
    secrets:
      WPORG_SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
