# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      deploy:
        required: true
        default: false
        type: boolean
        description: Deploy the release to WordPress.org
      version:
        required: true
        type: string
        description: The version number of the release

concurrency: WordPress.org

permissions:
  contents: read
  issues: write

jobs:
  test:
    name: Deploy Tag
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-tag.yml@trunk
    with:
      plugin: query-monitor
      readme: readme.txt
      version: ${{ github.event_name != 'workflow_dispatch' && github.event.release.tag_name || github.event.inputs.version }}
      deploy: ${{ github.event_name != 'workflow_dispatch' }}
    secrets:
      WPORG_SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
